title: Madeeha Khan
logo: assets/circle headshot.png



Description: I'm Madeeha, a UC Berkeley Regents’ and Chancellor’s Scholar (awarded to the top 1% of freshman applicants) and a first generation college graduate. My journey has been shaped by my commitment to leveraging technology for positive change, particularly in balancing out gender inequality through outreach in tech for young girls and underrepresented students. Through advocacy work and hands on engagement, I strive to close these gaps and create opportunities. 

show_downloads: false
theme: jekyll-theme-minimal
