title: Madeeha Khan
logo: assets/circle headshot.png



description: "I'm Madeeha, a UC Berkeley Regents’ and Chancellor’s Scholar and first-generation college graduate, passionate about using technology to drive social impact and promote equity in STEM through outreach and advocacy."







show_downloads: false
theme: jekyll-theme-minimal
